### ISSUE TITLE
Multiple Movie/TV Show Sections

### ISSUE THREAD

**Issue by TerryTWT** [MizzleDK/Mizuu#549]
Would be very nice to be able to create multiple Movie or TV Show sections, like having a separate Kid's Movies section or Anime section.  Thanks

**Comment by mydevbox** [comment]
I would love this feature too. I just discovered Mizuu a few days ago because I was looking for an app that'd make it easy to play locally stored content for our family. I need to ability to keep my kids movies and tv in a different area so they don't accidentally stumble on a gruesome Game of Thrones episode or the like.

**Comment by jycr753** [comment]
Well last time I checked Mizzle Developer was really busy and now the repo is open to anyone to add those features :)

**Comment by MizzleDK** [comment]
While I know it's not ideal, most smartphones / tablets today have the option of creating multiple user accounts. You can install Mizuu on a kids profile and only add the "approved" content.

Closing this for now.
